name:                gray-extended
version:             1.5.4
github:              "mhwombat/gray-extended"
license:             BSD3
author:              "Amy de Buitléir"
maintainer:          "amy@nualeargais.ie"
copyright:           "2018 Amy de Buitléir"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Gray encoding schemes
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mhwombat/gray-extended#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  gray-extended-test:
    main:                TestMain.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gray-extended
    - test-framework
    - test-framework-quickcheck2
    - QuickCheck
